travis:
  secure:
    BINSTAR_TOKEN: cYd9PDPIVChql9dkPGPv2NUATghbMMH0kYPBl1Lp1VkdART0FWPu10l/JNKxV9qF6Tsx/i6WWJbtmI09QXv37HFpSajr5z6UfQIAXy96l8EIBE8RipIREwzr76DDbYhSETI1Vbs1HuWPJWDxXtYJim8XCWMWxuYf1CZChTivOyBFsKqph+3fJ49CYH+CZ2T0qIqBvkAYI+GfORrK4AY7hdjvVSnLuVRuqFTT8cdUv1w0ToIg/Tkr+M0ybdNoN2/BWPrrH59quK92YwxRETm49Dv0Y1gcDiaTa3dKHJ6kV63KdaibtmVqYpAlGBNROFYKX7/S+XCrfjApPxDSenACjn28LvmyOl6ZjUn340EzM8xVjoRBWJ4gmQgQnNRunDr95OhP9+XtvX3Vi4kyXjFH+Y9NhLLj3K7Z7Ody0RRbhhs96Id0z5bDAtp4nU0npg2zGc6uvS5KCCg6cuTw90KsdshRrGXFXTSlChEPjcr37iXuoPAceXCjH1GEtc/urHsapeH+atLB1q+3damUVm74jIVetrET7RxDyZXN2sOgh/z86t5eXd72dn6W0ZYO4ZyuWHx5Lo5sJ9OD9AxxdO/hkmQt4mL/flHMsO+JJ9ToZ5lw3HHMvf0s8mKgUoJaw5UYjAScQMpwdK5UCETzSJqsRhi3w49H9TgIXBN72AylO3o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
